package calc_val;


/**
* calc_val/calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* Friday, February 5, 2021 3:53:44 PM CST
*/

public interface calc extends calcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calc
